mutation UpdateCustomerData($id: uuid!, $address: String, $name: String) {
	update_customers_by_pk(
		pk_columns: { id: $id }
		_set: { address: $address, name: $name }
	) {
		address
		id
		name
		phone
	}
}
